[package]
name = "restrust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
sha2 = "0.10"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
mysql = "*"
tokio = { version = "1", features = ["full"] }
chrono = "*"
